### ISSUE TITLE
Rulette - A simple and versatile rule engine

### ISSUE THREAD

**Issue by kislayverma** [grofers/talks#1]
# Title
Rulette - A simple and versatile rule engine

## Description
Rulette is an open source rule engine that I implemented some time ago. It is a lightweight rule definition, persistence, and evaluation library that covers most types of business rule management scenarios with extreme ease of setup and use. The talk will cover the motivation in building, design details, and a case study of how Rulette can be used for a real life use-case.

## Duration
- [ ] 30 min
- [x] 45 min

## Audience
The talk is suitable for all levels, and especially useful for developers working on system which has lots of variant behaviour depending on dynamic input.

## Outline
- What are rule engines and why we should use them.
- Why another rule engine (aka why you don't really need all that power)
- Rulette design and internal details
- Case Study

## Additional notes
Rulete Repository - https://github.com/kislayverma/Rulette

---

- [ ] Don't record this talk.
> Check this if you don't want your talk to be recorded.

**Comment by vinayak-mehta** [comment]
@kislayverma Are you available to give this talk at this weekend's meetup?

**Comment by kislayverma** [comment]
I am available for Saturday April 20.

**Comment by vinayak-mehta** [comment]
Awesome, adding this talk to the agenda. See you there!
