### ISSUE TITLE
Jenkins Pipeline

### ISSUE THREAD

**Issue by MovingToWeb** [grofers/talks#13]
# Title
Jenkins Pipeline

## Description
Jenkins is one of the most successful open source projects used by Enterprises. With DevOps league, Jenkins has upscaled their game to provide **Pipeline as a Code** where the whole workflow of the build process is controlled via Code. 
In this talk, we shall understand what is Jenkins Pipeline and how enterprises are using Jenkins Pipeline to adopt the DevOps culture.

## Duration
- [] 30 min
- [x] 45 min

## Audience
This talk is for a beginner who wants to know what is Jenkins Pipeline.

### Agenda:
- A real life analogy of Continuous Integration and Continuous Deployment.
- What is Jenkins Pipeline? 
- How are Pipelines different from a normal Jenkins Job.
- Multi branch Pipeline
- How enterprises use Jenkins Pipeline to achieve End to End automation.
If time permits, I will show a live demo in onboarding a Spring Boot Application to Jenkins Pipeline.

## Additional notes
I'm Ajay. I'm a Polyglot Programmer, Solutions Architect at JP Morgan Chase - [Profile](https://www.linkedin.com/in/movingtoweb/). 
As a hobby, I have been creating educational videos on new Technologies in the Youtube Channel - [TechPrimers](https://www.youtube.com/TechPrimers) for the last 3 years. 

---

- [ ] Don't record this talk.
I have no objection in recording this talk

**Comment by vinayak-mehta** [comment]
@MovingToWeb Are you available to give this talk on Saturday?

**Comment by MovingToWeb** [comment]
Yes @vinayak-mehta
I'm available

**Comment by vinayak-mehta** [comment]
Awesome, see you on Saturday!

**Comment by vinayak-mehta** [comment]
@MovingToWeb Can you comment the slides link here? Thanks for the talk!

**Comment by MovingToWeb** [comment]
Thanks for the hospitality 
Slides: https://drive.google.com/open?id=12wJEI-bw4PWSDp3HYsj5r6eqPNGCnJvGyUZAzBjq-6A
Github: https://github.com/TechPrimers/grofers-talks-jenkins
