### ISSUE TITLE
ML Bias

### ISSUE THREAD

**Issue by amrrs** [grofers/talks#14]
# Title
> Machine Learning Bias

## Description
> Humans are filled with unconscious biases and when these are fed into Machine to Learn in the form of Data, the resulting AI model wouldn't be `fair` enough without Biases. This talk tries to introduce you to the world of Machine Learning Bias. 

## Duration
- [x] 30 min
- [ ] 45 min

## Audience
> Those are interested Machine Learning and stuff around it

## Outline
> https://speakerdeck.com/amrrs/machine-learning-bias

## Additional notes
> https://speakerdeck.com/amrrs/machine-learning-bias

---

- [ ] Don't record this talk.
> Check this if you don't want your talk to be recorded.

**Comment by vinayak-mehta** [comment]
See you tomorrow!

**Comment by vinayak-mehta** [comment]
@amrrs Thanks for the talk!
