### ISSUE TITLE
R in the Real World

### ISSUE THREAD

**Issue by amrrs** [grofers/talks#2]
# Title
R in the Real World

## Description
This talk contains two sections predominantly - 1st explaining what's all (non-obvious) that are possible with R and 2nd, How well-known organizations are using R in their company. 
* R is one of the most popular programming languages preferred in Data Science / Analytics. 

## Duration
- [x] 30 min
- [x] 45 min

## Audience
This is a not-so-technical talk so doesn't matter much of audience technical expertise. Nevertheless, Can be more useful for people who are part of Data Science team or trying to get into. 

## Outline
https://github.com/amrrs/RinTheRealWorld/blob/master/slides_top_view.png

## Additional notes
https://github.com/amrrs/RinTheRealWorld 

---

- [ ] Don't record this talk.
> Check this if you don't want your talk to be recorded.

**Comment by vinayak-mehta** [comment]
@amrrs I'm reopening this, you can give this talk in a future meetup!

**Comment by amrrs** [comment]
Oh cool!

**Comment by vinayak-mehta** [comment]
@amrrs Thanks for the talk!
