### ISSUE TITLE
Introduction to Tweets Analysis (Twitter Analytics) in R

### ISSUE THREAD

**Issue by amrrs** [grofers/talks#3]
# Title
Introduction to Tweets Analysis in R

## Description
Basic introduction of how text analytics could be performed on Tweets. This talk takes audience through a project of analysis tweets about Hasan Minhaj's Patriot Act. 

## Duration
- [x] 30 min
- [x] 45 min

## Audience
Good to have Basic knowledge of R and Text / Data Analytics (not mandatory though)

## Outline
+ Text Analytics
+ Twitter Data Format
+ Text Analytics + Tweets
+ Presentation

## Additional notes
https://github.com/amrrs/hasan_india_tweets_analysis

---

- [ ] Don't record this talk.
> Check this if you don't want your talk to be recorded.

**Comment by vinayak-mehta** [comment]
@amrrs Are you available to give this talk at this weekend's meetup?

**Comment by amrrs** [comment]
Yes @vinayak-mehta . Guess it's on 20th right ?

**Comment by vinayak-mehta** [comment]
Yes. Adding this talk to the agenda. See you there!

**Comment by amrrs** [comment]
You're expecting it to be 30 min or 45 mins

**Comment by vinayak-mehta** [comment]
30 minutes.

**Comment by amrrs** [comment]
Noted!

**Comment by amrrs** [comment]
Hey @vinayak-mehta Just came across this post. https://lambda.grofers.com/community-update-march-2019-bangalore-7c8e198b5a7a Nice one!
