### ISSUE TITLE
Python: tooling, Code profiling and Security

### ISSUE THREAD

**Issue by arunsingh** [grofers/talks#6]
# Title
> Python: tooling, Code profiling and Security

## Description
> This talk will discuss how to write clean code in python using tooling ecosystem and doing sanity checks for security. (250 words)

## Duration
- [ ] 30 min
- [x] 45 min

## Audience
> Prerequisites: Python Know how. Additionally, talk content covers a beginner, intermediate and advanced audience.

## Outline
> Python tooling ecosystem
> Doing Code profiling
> Building security inside the code

## Additional notes
> You personal details, links to previous talks, etc.
https://twitter.com/aruns89
https://linkedin.com/in/arunsingh23
---

- [ ] Don't record this talk.
> Check this if you don't want your talk to be recorded.

**Comment by vinayak-mehta** [comment]
@arunsingh Are you available to present this on Saturday?

**Comment by arunsingh** [comment]
Yeah I am available.

**Comment by vinayak-mehta** [comment]
Can you add more details under each section of your outline? For example, the list of tools in the current ecosystem etc.

**Comment by vinayak-mehta** [comment]
See you on Saturday at 10am!
